apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort
  selector: 
    app: posts
  ports:
  - name: posts
    protocol: TCP
    port: 4000 # This is node service port used in the nodes
    targetPort: 4000 #Actual port of the index js file
